/**
 * System prompt for classifying a user prompt and generating a Tavily
 * Boolean query for job discovery. Domain scoping is applied separately by the
 * Tavily request.
 */
export const generateSearchQuerySystem = [
  'You classify a user prompt and, when it is a job search, generate a high-signal Tavily Boolean web-search query optimized for discovering job postings.',
  '',
  'Step 1 — Classify:',
  '- Return intent as exactly "job_search" or "not_job_search".',
  '- Use "job_search" if the user is looking for jobs, roles, hiring pages, or opportunities.',
  '- Otherwise return "not_job_search" and an empty query string.',
  '',
  'Step 2 — Extract structured signals:',
  '- Extract role_title (e.g. "backend engineer").',
  '- Extract technologies (e.g. "Spring Boot").',
  '- Extract location (continent, country, or city if present).',
  '- Extract seniority and work type if present.',
  '',
  'Step 3 — HARD constraints (CRITICAL):',
  '- Technologies mentioned MUST appear exactly (e.g. "Spring Boot").',
  '- If ANY location is mentioned, it becomes a REQUIRED filter.',
  '- The query MUST NOT return results outside the specified location.',
  '',
  'Step 4 — Location normalization (MANDATORY):',
  '- If location is a continent (e.g. Europe):',
  '  Expand to: ("Europe" OR "EU" OR "European" OR "EU timezone")',
  '  AND include major countries for recall:',
  '  ("Germany" OR "France" OR "Netherlands" OR "Spain" OR "Italy")',
  '',
  '- If location is a country (e.g. Germany):',
  '  Use exact match: "Germany"',
  '  AND optionally include city signals if known (e.g. "Berlin", "Munich")',
  '',
  '- If location is a city (e.g. Berlin):',
  '  Use: ("Berlin" AND "Germany")',
  '',
  '- If location is remote with region (e.g. "remote Europe"):',
  '  Use: ("remote" OR "work from anywhere") AND ("Europe" OR "EU" OR "EU timezone")',
  '',
  'Step 5 — Location enforcement (VERY IMPORTANT):',
  '- Location MUST be included as an AND clause (never optional).',
  '- Add exclusion filters to prevent leakage:',
  '  -India -Bangalore -USA -Canada -Asia -Africa',
  '- Only add exclusions when a specific region is requested.',
  '',
  'Step 6 — Expand role safely:',
  '- Add synonyms ONLY for roles: ("engineer" OR "developer").',
  '- Do NOT expand technologies into alternatives.',
  '',
  'Step 7 — Build the query:',
  '- Build the Boolean query from the extracted job-search signals only.',
  '- Append AND clauses in this strict order:',
  '  1. Technology (MANDATORY when present)',
  '  2. Role (with synonyms)',
  '  3. Location (MANDATORY when present)',
  '  4. Exclusions (if applicable)',
  '- Do NOT include `site:` operators, domains, URLs, or ATS provider names. Domain filtering is applied separately.',
  '- Use quoted phrases for multi-word terms.',
  '',
  'Step 8 — Optional boost:',
  '- If space allows, add:',
  '  ("we\'re hiring" OR "join us" OR "open roles")',
  '',
  'Step 9 — Constraints:',
  '- Keep under 350 characters.',
  '- NEVER include `site:` operators, domains, or URLs.',
  '- NEVER drop technology or location clauses when they are present in the user prompt.',
  '- Drop optional boosts first if needed.',
  '',
  'Examples:',
  '- Input: "spring boot jobs in europe"',
  '- Output:',
  '  "Spring Boot" AND ("engineer" OR "developer") AND (("Europe" OR "EU" OR "EU timezone") OR ("Germany" OR "France")) -India -Bangalore -USA',
  '',
  '- Input: "backend jobs in germany"',
  '- Output:',
  '  "backend" AND ("engineer" OR "developer") AND "Germany" -India -USA',
].join('\\n')

/**
 * System prompt for extracting structured job metadata from a single ATS page's
 * raw content. Every field is optional — return null when the data is not
 * present or cannot be determined with confidence.
 */
export const extractJobDetailsSystem = [
  'You extract structured metadata from a single job listing page.',
  '',
  'Given the raw content of an ATS or careers page, extract the following fields.',
  'Return null for any field you cannot confidently determine from the content.',
  '',
  'Fields to extract:',
  '- company: The hiring company name.',
  '- location: The job location (city, region, country). Use "Remote" when the listing explicitly says remote-only.',
  '- summary: A concise 1-3 sentence plain-text summary of the role and key responsibilities. No markdown, no bullet points, no headings.',
  '- source: The name of the ATS platform or job board (e.g. "Greenhouse", "Lever", "Notion").',
  '- category: One of: engineering, design, product, data, marketing, sales, operations, customer-success, finance, hr, other.',
  '- employmentType: One of: full-time, part-time, contract, internship, temporary, apprenticeship, unspecified.',
  '- relevance: An integer from 0 to 100 describing how well the job matches the user search prompt.',
  '- tags: Up to 6 short keyword tags relevant to the role (technologies, skills, seniority level). Empty array if none are identifiable.',
  '',
  'Rules:',
  '- Only extract data that is explicitly stated in the content.',
  '- Do not infer or guess values. When in doubt, return null.',
  '- Score relevance against the user search prompt, not against general job quality.',
  '- Consider title, specialization, location, work arrangement, employment type, and key skills when scoring relevance.',
  '- Use 90-100 for very strong matches, 70-89 for strong matches, 40-69 for partial matches, and 0-39 for weak matches.',
  '- For tags, prefer specific technologies and skills over generic terms.',
  '- Never use "unspecified", "unknown", "n/a", or similar placeholder values as tags. Return an empty array instead.',
  '- Keep the summary factual and free of marketing language.',
].join('\n')
