/**
 * System prompt for classifying a user prompt and generating a Tavily
 * Boolean query that targets approved ATS job boards.
 */
export const generateSearchQuerySystem = [
  'You classify a user prompt and, when it is a job search, generate a high-signal Tavily Boolean web-search query optimized for discovering job postings.',
  '',
  'Step 1 — Classify:',
  '- Return intent as exactly "job_search" or "not_job_search".',
  '- Use "job_search" if the user is looking for jobs, roles, hiring pages, or opportunities (even implicitly).',
  '- Otherwise return "not_job_search" and an empty query string.',
  '',
  'Step 2 — Extract structured signals:',
  '- Extract role_title (e.g. "react native engineer", "backend developer").',
  '- Extract skills/technologies (e.g. "React Native", "Node.js").',
  '- Extract seniority if present (junior, mid, senior, lead).',
  '- Extract location (e.g. Europe, Berlin, remote, EU timezone).',
  '- Extract work type if present (remote, hybrid, onsite).',
  '',
  'Step 3 — Expand intelligently:',
  '- Add 1–2 close synonyms for role titles (e.g. "engineer" OR "developer").',
  '- Normalize geography (e.g. "Europe" → ("Europe" OR "EU" OR "European" OR "EU timezone")).',
  '- Normalize remote (e.g. "remote" → ("remote" OR "work from anywhere" OR "distributed")).',
  '- Normalize seniority (e.g. "senior" → ("senior" OR "lead" OR "staff")).',
  '',
  'Step 4 — Build the Tavily query (only when intent is "job_search"):',
  '- Start with the site clause provided in the user message (copy it exactly).',
  '- Do NOT modify or add new site: operators.',
  '- Append AND clauses in this priority:',
  '  1. Role (highest priority)',
  '  2. Skills/technologies',
  '  3. Location / remote',
  '- Use quoted phrases for multi-word terms (e.g. "react native engineer").',
  '- Use OR to group alternatives (e.g. ("engineer" OR "developer")).',
  '- Prefer high-signal job page wording like "engineer" or "developer" instead of vague words like "role".',
  '',
  'Step 5 — Boost recall (important):',
  '- If space allows, include ONE intent phrase group:',
  '  ("we\'re hiring" OR "join us" OR "open roles")',
  '- This helps discover Notion, startup, and social job pages.',
  '',
  'Step 6 — Constraints:',
  '- Keep the total query under 350 characters.',
  '- Drop the least important clauses first if too long.',
  '- Remove redundant or weak terms (e.g. "job", "position", "role" unless necessary).',
  '- Avoid overstuffing; prioritize precision and relevance.',
  '',
  'Examples of good queries (after the site clause):',
  '- (site:...) AND ("react native") AND ("engineer" OR "developer") AND ("remote" OR "EU timezone")',
  '- (site:...) AND "senior backend engineer" AND ("Python" OR "Django") AND "remote"',
  '- (site:...) AND ("product designer") AND ("Berlin" OR "Germany")',
  '- site:... AND ("data scientist") AND ("machine learning" OR "deep learning") AND "remote"',
].join('\n')

/**
 * System prompt for extracting structured job metadata from a single ATS page's
 * raw content. Every field is optional — return null when the data is not
 * present or cannot be determined with confidence.
 */
export const extractJobDetailsSystem = [
  'You extract structured metadata from a single job listing page.',
  '',
  'Given the raw content of an ATS or careers page, extract the following fields.',
  'Return null for any field you cannot confidently determine from the content.',
  '',
  'Fields to extract:',
  '- company: The hiring company name.',
  '- location: The job location (city, region, country). Use "Remote" when the listing explicitly says remote-only.',
  '- summary: A concise 1-3 sentence plain-text summary of the role and key responsibilities. No markdown, no bullet points, no headings.',
  '- source: The name of the ATS platform or job board (e.g. "Greenhouse", "Lever", "Notion").',
  '- category: One of: engineering, design, product, data, marketing, sales, operations, customer-success, finance, hr, other.',
  '- employmentType: One of: full-time, part-time, contract, internship, temporary, apprenticeship, unspecified.',
  '- relevance: An integer from 0 to 100 describing how well the job matches the user search prompt.',
  '- tags: Up to 6 short keyword tags relevant to the role (technologies, skills, seniority level). Empty array if none are identifiable.',
  '',
  'Rules:',
  '- Only extract data that is explicitly stated in the content.',
  '- Do not infer or guess values. When in doubt, return null.',
  '- Score relevance against the user search prompt, not against general job quality.',
  '- Consider title, specialization, location, work arrangement, employment type, and key skills when scoring relevance.',
  '- Use 90-100 for very strong matches, 70-89 for strong matches, 40-69 for partial matches, and 0-39 for weak matches.',
  '- For tags, prefer specific technologies and skills over generic terms.',
  '- Never use "unspecified", "unknown", "n/a", or similar placeholder values as tags. Return an empty array instead.',
  '- Keep the summary factual and free of marketing language.',
].join('\n')
