import { createClient } from '@convex-dev/better-auth'
import { convex } from '@convex-dev/better-auth/plugins'
import type { GenericCtx } from '@convex-dev/better-auth/utils'
import type { BetterAuthOptions } from 'better-auth'
import { betterAuth } from 'better-auth'
import { components } from '../_generated/api'
import type { DataModel } from '../_generated/dataModel'
import { getRequiredEnv } from '../shared/env'
import authConfig from '../auth.config'
import schema from './schema'

// components.betterAuth is generated by `npx convex dev` after registering the
// component in app.config.ts. Until codegen runs, this will show a TS error.
export const authComponent = createClient<DataModel, typeof schema>(
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (components as any).betterAuth,
  {
    local: { schema },
    verbose: false,
  },
)

export const createAuthOptions = (ctx: GenericCtx<DataModel>) => {
  return {
    appName: 'Jobsite',
    baseURL: getRequiredEnv('SITE_URL'),
    secret: getRequiredEnv('BETTER_AUTH_SECRET'),
    database: authComponent.adapter(ctx),
    socialProviders: {
      google: {
        clientId: getRequiredEnv('GOOGLE_CLIENT_ID'),
        clientSecret: getRequiredEnv('GOOGLE_CLIENT_SECRET'),
      },
    },
    plugins: [convex({ authConfig })],
  } satisfies BetterAuthOptions
}

export const createAuth = (ctx: GenericCtx<DataModel>) => {
  return betterAuth(createAuthOptions(ctx))
}
